#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ $0 != "utils/import-all" ]]; then
	echo "ERROR: Must be run from repo root." >&2
	exit 1
fi

if [ $# -ne 0 ]; then
	echo "Overwrite all repo files with installed files."
	echo "Usage: $0"
	exit
fi

cat <(find dotfiles -not -type d) \
    <(find bin -not -type d) \
    <(find complete -not -type d) | xargs utils/import
